name: "Podcast Generator"
author: "Ray Villalbobs kinda"
description: "Generates a feed for a podcast from a YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email: 
    descrption: "the commiter's emails address"
    required: true
    default: ${{ github.actor }}@localhost
  name:
    descrption: "the commiter's name"
    required: true
    default: ${{ github.actor }}
